"""Shared PDF and SharePoint pipeline tests using an in-memory Graph boundary."""

import re
import json
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from invoice_settings import Settings
from domain import InvoiceRequest, RandomGenerationRequest
from errors import SharePointError
from invoice_service import InvoiceGenerationService
from sharepoint_service import GenerationActor, GraphClient, REQUIRED_COLUMNS, SharePointInvoiceService


class FakeGraph:
    def __init__(self):
        self.items = {}
        self.files = {}
        self.drive_id = "drive-id"
        self.metadata_updates = 0
        self.fail_metadata_update = None
        self.columns = [
            {"displayName": name, "name": name.replace(" ", "_"), **({"personOrGroup": {}} if name == "Generated By" else {})}
            for name in REQUIRED_COLUMNS
        ]

    def request(self, method, path, data=None, content_type="application/json"):
        base = "/sites/site-id/lists/library-id"
        if method == "GET" and path == base:
            return {"displayName": "Invoice Library", "webUrl": "https://contoso.sharepoint.com/sites/demo/InvoiceLibrary"}
        if method == "GET" and path == base + "/drive":
            return {"id": self.drive_id}
        if method == "GET" and path.startswith("/drives/b%21drive-id?"):
            return {"id": "b!drive-id", "sharepointIds": {"listId": "library-id"}}
        if method == "GET" and path.startswith(base + "/columns"):
            return {"value": self.columns}
        if method == "PATCH" and path.endswith("/fields"):
            self.metadata_updates += 1
            if self.metadata_updates == self.fail_metadata_update:
                raise SharePointError("Metadata update failed.")
            item_id = re.search(r"/items/([^/]+)/fields$", path).group(1)
            self.items[item_id]["fields"].update(data)
            return data
        if method == "GET" and "/items/" in path and path.endswith("?$expand=fields"):
            item_id = re.search(r"/items/([^/?]+)", path).group(1)
            return self.items[item_id]
        if method == "GET" and path.startswith(base + "/items?$expand=fields"):
            return {"value": list(self.items.values())}
        if method == "DELETE" and path.startswith("/drives/drive-id/items/"):
            drive_id = path.rsplit("/", 1)[-1]
            self.files.pop(drive_id, None)
            self.items.pop(drive_id.removeprefix("drive-"), None)
            return {}
        raise AssertionError((method, path))

    def upload_unique(self, drive_id, filename, pdf_bytes):
        assert drive_id == "drive-id"
        assert pdf_bytes.startswith(b"%PDF")
        assert filename not in (entry[0] for entry in self.files.values())
        item_id = str(len(self.items) + 1 + self.metadata_updates)
        drive_item_id = "drive-" + item_id
        self.files[drive_item_id] = (filename, pdf_bytes)
        self.items[item_id] = {
            "id": item_id,
            "webUrl": f"https://contoso.sharepoint.com/sites/demo/InvoiceLibrary/{filename}",
            "fields": {},
        }
        return {"id": drive_item_id, "sharepointIds": {"listItemId": item_id}}


def settings(**overrides):
    environment = {
        "SHAREPOINT_SITE_ID": "site-id",
        "SHAREPOINT_LIBRARY_ID": "library-id",
        "SHAREPOINT_LIBRARY_NAME": "Invoice Library",
        "SHAREPOINT_USER_LOOKUP_IDS": '{"local@example.test": 17}',
        "INVOICE_MAX_BATCH_SIZE": "50",
    }
    environment.update(overrides)
    return Settings.from_env(environment)


class SharePointPipelineTests(unittest.TestCase):
    def setUp(self):
        self.settings = settings()
        self.graph = FakeGraph()
        self.sharepoint = SharePointInvoiceService(self.settings, self.graph)
        self.generator = InvoiceGenerationService(self.settings, self.sharepoint)
        self.actor = GenerationActor("Local Tester", email="local@example.test")

    def test_random_batches_store_exact_counts_and_unique_payloads(self):
        for count in (3, 5, 10):
            with self.subTest(count=count):
                batch = self.generator.generate_random(RandomGenerationRequest(count, "UAT"), self.actor)
                self.assertEqual((batch.requested_count, batch.generated_count, batch.uploaded_count, batch.failed_count), (count, count, count, 0))
                invoices = [record.invoice for record in batch.sharepoint_records]
                self.assertEqual(len({invoice.invoice_number for invoice in invoices}), count)
                self.assertEqual(len({invoice.batch_id for invoice in invoices}), 1)
                self.assertEqual(len({(invoice.seller.name, invoice.buyer.name) for invoice in invoices}), count)
                self.assertEqual(len({invoice.totals.grand_total for invoice in invoices}), count)
                self.assertEqual(len({invoice.totals.tax.igst + invoice.totals.tax.cgst + invoice.totals.tax.sgst for invoice in invoices}), count)
                self.assertEqual(len(batch.sharepoint_links), count)
                for record in batch.sharepoint_records:
                    metadata = self.graph.items[record.item_id]["fields"]
                    self.assertEqual(len(metadata), len(REQUIRED_COLUMNS))
                    self.assertEqual(metadata["Invoice_Number"], record.invoice.invoice_number)
                    self.assertEqual(metadata["Batch_ID"], batch.batch_id)
                    self.assertEqual(metadata["Generated_ByLookupId"], "17")
                    self.assertEqual(metadata["Total_Amount"], float(record.invoice.totals.grand_total))
                    self.assertIn(record.invoice.invoice_number + ".pdf", [entry[0] for entry in self.graph.files.values()])

    def test_custom_batch_uses_same_pipeline_and_searches_sharepoint(self):
        request = InvoiceRequest.from_form({
            "invoice_type": "GST", "purpose": "Demo", "generation_mode": "Batch", "count": "3",
            "date_from": "2026-09-01", "date_to": "2026-09-30",
            "min_amount": "1000", "max_amount": "10000",
            "tax_type": "IGST", "tax_rate": "18",
            "seller_name": "Custom Seller", "seller_address": "Seller Road", "seller_tax_id": "SELLER-TAX",
            "buyer_name": "Custom Buyer", "buyer_address": "Buyer Street", "buyer_tax_id": "BUYER-TAX",
        })
        batch = self.generator.generate_custom(request, self.actor)
        self.assertEqual(batch.uploaded_count, 3)
        self.assertEqual(len(self.sharepoint.list_batch_invoices(batch.batch_id)), 3)
        invoices = [record.invoice for record in batch.sharepoint_records]
        self.assertEqual({(invoice.seller.name, invoice.seller.address, invoice.seller.tax_id) for invoice in invoices}, {("Custom Seller", "Seller Road", "SELLER-TAX")})
        self.assertEqual({(invoice.buyer.name, invoice.buyer.address, invoice.buyer.tax_id) for invoice in invoices}, {("Custom Buyer", "Buyer Street", "BUYER-TAX")})
        self.assertEqual({invoice.totals.tax.rate for invoice in invoices}, {request.tax_rate})
        self.assertEqual(len({invoice.invoice_date for invoice in invoices}), 1)
        self.assertEqual(len({tuple(item.description for item in invoice.line_items) for invoice in invoices}), 1)
        self.assertEqual(len({invoice.totals.grand_total for invoice in invoices}), 3)
        first = batch.sharepoint_records[0]
        self.assertEqual(self.sharepoint.get_invoice_by_number(first.invoice.invoice_number).web_url, first.web_url)
        self.assertEqual(self.sharepoint.get_invoice(first.item_id).metadata["Generated By"], "17")
        self.assertEqual(len(self.sharepoint.search_invoice_metadata("Show me Demo invoices")), 3)

    def test_metadata_failure_is_reported_and_uploaded_file_removed(self):
        self.graph.fail_metadata_update = 2
        batch = self.generator.generate_random(RandomGenerationRequest(3, "Testing"), self.actor)
        self.assertEqual((batch.generated_count, batch.uploaded_count, batch.failed_count), (3, 2, 1))
        self.assertEqual(len(batch.failed_items), 1)
        self.assertEqual(batch.failed_items[0].stage, "sharepoint")
        self.assertEqual(len(self.graph.files), 2)
        self.assertEqual(len(self.sharepoint.list_batch_invoices(batch.batch_id)), 2)

    def test_no_person_identity_fails_before_rendering_or_upload(self):
        no_person = SharePointInvoiceService(settings(SHAREPOINT_USER_LOOKUP_IDS="{}"), self.graph)
        generator = InvoiceGenerationService(self.settings, no_person)
        with self.assertRaisesRegex(SharePointError, "Person"):
            generator.generate_random(RandomGenerationRequest(3, "Testing"), GenerationActor("Unmapped User"))
        self.assertFalse(self.graph.files)

    def test_configured_user_mapping_resolves_person(self):
        self.assertEqual(self.sharepoint.preflight(self.actor), 17)

    def test_site_user_email_resolves_person_without_mapping(self):
        service = SharePointInvoiceService(settings(SHAREPOINT_USER_LOOKUP_IDS="{}"), self.graph)
        actor = GenerationActor("Site User", email="site@example.test")
        with patch.object(service, "_site_users", return_value=({"id": "31", "fields": {"EMail": actor.email}},)):
            self.assertEqual(service.preflight(actor), 31)

    def test_missing_column_fails_before_upload(self):
        self.graph.columns = [column for column in self.graph.columns if column["displayName"] != "Tax Type"]
        with self.assertRaisesRegex(SharePointError, "Tax Type"):
            self.generator.generate_random(RandomGenerationRequest(3, "Testing"), self.actor)
        self.assertFalse(self.graph.files)

    def test_configured_drive_id_resolves_library_list_once(self):
        self.graph.drive_id = "b!drive-id"
        service = SharePointInvoiceService(settings(SHAREPOINT_LIBRARY_ID="b!drive-id"), self.graph)
        service._ensure_schema()
        self.assertEqual(service._list_id, "library-id")
        self.assertEqual(service._drive_id, "b!drive-id")
        self.assertEqual(service._base(), "/sites/site-id/lists/library-id")

    def test_missing_graph_credentials_fail_before_network_access(self):
        with self.assertRaisesRegex(SharePointError, "credentials"):
            GraphClient(self.settings)._token()

    def test_invalid_client_secret_has_actionable_error(self):
        configured = settings(
            SHAREPOINT_GRAPH_TENANT_ID="tenant-id",
            SHAREPOINT_GRAPH_CLIENT_ID="client-id",
            SHAREPOINT_GRAPH_CLIENT_SECRET="invalid-secret",
        )
        with patch("sharepoint_service.msal.ConfidentialClientApplication") as application:
            application.return_value.acquire_token_for_client.return_value = {
                "error": "invalid_client",
                "error_description": "AADSTS7000215: Invalid client secret provided.",
            }
            with self.assertRaisesRegex(SharePointError, "secret Value, not its Secret ID"):
                GraphClient(configured)._token()

    def test_upload_session_fails_on_name_conflict_and_sends_no_token_to_upload_url(self):
        client = GraphClient(self.settings)
        class Response:
            def __enter__(self):
                return self
            def __exit__(self, *_args):
                return False
            def read(self):
                return json.dumps({"id": "drive-item-1"}).encode()
        with patch.object(client, "request", return_value={"uploadUrl": "https://upload.example.test/session"}) as create, patch("sharepoint_service.urllib.request.urlopen", return_value=Response()) as upload:
            result = client.upload_unique("drive-id", "INV_GST_UAT_001.pdf", b"%PDF-test")
        self.assertEqual(result["id"], "drive-item-1")
        self.assertEqual(create.call_args.args[2]["item"]["@microsoft.graph.conflictBehavior"], "fail")
        request = upload.call_args.args[0]
        self.assertEqual(request.get_method(), "PUT")
        self.assertNotIn("Authorization", request.headers)
        self.assertEqual(request.headers["Content-range"], "bytes 0-8/9")


if __name__ == "__main__":
    unittest.main()
