"""SharePoint Invoice Library access through Microsoft Graph v1.0."""

from __future__ import annotations

import json
import logging
import re
import threading
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Iterable, Mapping
from uuid import UUID

import msal

from config import Settings
from domain import Invoice, StoredInvoice
from errors import SharePointError


logger = logging.getLogger(__name__)
GRAPH_ROOT = "https://graph.microsoft.com/v1.0"
REQUIRED_COLUMNS = (
    "Invoice Number", "Generated Date", "Purpose", "Invoice Type", "Batch ID",
    "Generated By", "Seller Name", "Buyer Name", "Total Amount", "Tax Type",
)


@dataclass(frozen=True)
class GenerationActor:
    display_name: str
    aad_object_id: str | None = None
    email: str | None = None


@dataclass(frozen=True)
class SearchRecord:
    item_id: str
    web_url: str
    metadata: dict[str, Any]


class GraphClient:
    """Small Graph transport; credentials never enter bot activities or logs."""

    def __init__(self, settings: Settings):
        self.settings = settings
        self._application: msal.ConfidentialClientApplication | None = None

    def _token(self) -> str:
        if not all((self.settings.graph_tenant_id, self.settings.graph_client_id, self.settings.graph_client_secret)):
            raise SharePointError("SharePoint Graph credentials are not configured.")
        try:
            if self._application is None:
                self._application = msal.ConfidentialClientApplication(
                    self.settings.graph_client_id,
                    authority=f"https://login.microsoftonline.com/{self.settings.graph_tenant_id}",
                    client_credential=self.settings.graph_client_secret,
                )
            result = self._application.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])
        except Exception as exc:
            logger.exception("graph_token_request_failed")
            raise SharePointError("SharePoint authentication could not be reached.") from exc
        if "access_token" not in result:
            error_description = str(result.get("error_description") or "")
            match = re.search(r"AADSTS\d+", error_description)
            error_code = match.group() if match else "unknown"
            logger.error("graph_token_failed error=%s entra_code=%s", result.get("error"), error_code)
            if error_code == "AADSTS7000215":
                raise SharePointError("SharePoint authentication failed: the client secret is invalid. Configure the secret Value, not its Secret ID, for the matching app registration.")
            raise SharePointError("SharePoint authentication failed. Check the configured Graph app credentials and site access.")
        return str(result["access_token"])

    def request(self, method: str, path: str, data: Any = None, content_type: str = "application/json") -> dict[str, Any]:
        url = path if path.startswith("https://") else GRAPH_ROOT + path
        parsed = urllib.parse.urlparse(url)
        if parsed.scheme != "https" or parsed.netloc != "graph.microsoft.com" or not parsed.path.startswith("/v1.0/"):
            raise SharePointError("An invalid Graph request URL was rejected.")
        body = data if isinstance(data, bytes) else json.dumps(data).encode("utf-8") if data is not None else None
        headers = {"Authorization": f"Bearer {self._token()}", "Accept": "application/json"}
        if body is not None:
            headers["Content-Type"] = content_type
        request = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=45) as response:
                raw = response.read()
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            try:
                error = json.loads(exc.read()).get("error", {})
                code = error.get("code", "unknown")
            except (ValueError, AttributeError):
                code = "unknown"
            logger.exception("graph_request_failed method=%s path=%s status=%s code=%s", method, parsed.path, exc.code, code)
            raise SharePointError(f"SharePoint request failed (HTTP {exc.code}, {code}).") from exc
        except (urllib.error.URLError, TimeoutError, OSError, ValueError) as exc:
            logger.exception("graph_request_failed method=%s path=%s", method, parsed.path)
            raise SharePointError("SharePoint could not be reached or returned an invalid response.") from exc

    def upload_unique(self, drive_id: str, filename: str, pdf_bytes: bytes) -> dict[str, Any]:
        if not pdf_bytes.startswith(b"%PDF") or len(pdf_bytes) > 10 * 1024 * 1024:
            raise SharePointError("The invoice PDF is invalid or exceeds the supported upload size.")
        drive = urllib.parse.quote(drive_id, safe="")
        name = urllib.parse.quote(filename, safe="")
        session = self.request(
            "POST",
            f"/drives/{drive}/root:/{name}:/createUploadSession",
            {"item": {"@microsoft.graph.conflictBehavior": "fail", "name": filename}},
        )
        upload_url = session.get("uploadUrl")
        if not isinstance(upload_url, str) or urllib.parse.urlparse(upload_url).scheme != "https":
            raise SharePointError("SharePoint did not return a secure upload session.")
        request = urllib.request.Request(
            upload_url,
            data=pdf_bytes,
            headers={"Content-Length": str(len(pdf_bytes)), "Content-Range": f"bytes 0-{len(pdf_bytes) - 1}/{len(pdf_bytes)}"},
            method="PUT",
        )
        try:
            with urllib.request.urlopen(request, timeout=90) as response:
                uploaded = json.loads(response.read())
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, OSError, ValueError) as exc:
            logger.exception("sharepoint_upload_session_failed filename=%s", filename)
            raise SharePointError("SharePoint rejected the PDF upload.") from exc
        if not isinstance(uploaded, dict) or not uploaded.get("id"):
            raise SharePointError("SharePoint did not confirm the PDF upload.")
        return uploaded


class SharePointInvoiceService:
    def __init__(self, settings: Settings, graph: GraphClient | None = None):
        self.settings = settings
        self.graph = graph or GraphClient(settings)
        self._lock = threading.Lock()
        self._drive_id: str | None = None
        self._list_id: str | None = None
        self._library_url: str | None = None
        self._columns: dict[str, dict[str, Any]] | None = None

    def _base_for_list(self, list_id: str) -> str:
        if not self.settings.sharepoint_site_id or not self.settings.sharepoint_library_id:
            raise SharePointError("SharePoint site and Invoice Library IDs must be configured.")
        site = urllib.parse.quote(self.settings.sharepoint_site_id, safe=",")
        library = urllib.parse.quote(list_id, safe="")
        return f"/sites/{site}/lists/{library}"

    def _base(self) -> str:
        self._ensure_schema()
        assert self._list_id is not None
        return self._base_for_list(self._list_id)

    def _pages(self, path: str, limit: int) -> Iterable[dict[str, Any]]:
        seen = 0
        while path and seen < limit:
            page = self.graph.request("GET", path)
            values = page.get("value")
            if not isinstance(values, list):
                raise SharePointError("SharePoint returned an invalid list response.")
            for item in values:
                if not isinstance(item, dict):
                    raise SharePointError("SharePoint returned an invalid list item.")
                yield item
                seen += 1
                if seen >= limit:
                    break
            next_link = page.get("@odata.nextLink") or ""
            if seen >= limit and next_link:
                raise SharePointError("The Invoice Library search limit was reached. Refine the query.")
            path = next_link

    def _ensure_schema(self) -> None:
        if self._columns is not None:
            return
        with self._lock:
            if self._columns is not None:
                return
            configured_id = self.settings.sharepoint_library_id
            if not configured_id:
                raise SharePointError("SharePoint site and Invoice Library IDs must be configured.")
            if configured_id.startswith("b!"):
                drive_path = "/drives/" + urllib.parse.quote(configured_id, safe="")
                configured_drive = self.graph.request("GET", drive_path + "?$select=id,name,webUrl,sharepointIds,driveType")
                list_id = (configured_drive.get("sharepointIds") or {}).get("listId")
                if not list_id:
                    list_id = self.graph.request("GET", drive_path + "/list").get("id")
                if not list_id:
                    raise SharePointError("The configured SharePoint drive ID did not expose its Invoice Library list ID.")
                logger.info("sharepoint_library_identifier_resolved type=drive")
            else:
                list_id = configured_id
                logger.info("sharepoint_library_identifier_resolved type=list")
            base = self._base_for_list(str(list_id))
            library = self.graph.request("GET", base)
            if str(library.get("displayName", "")).casefold() != self.settings.sharepoint_library_name.casefold():
                raise SharePointError("The configured library ID does not match Invoice Library.")
            drive = self.graph.request("GET", base + "/drive")
            drive_id = drive.get("id")
            if not drive_id or not library.get("webUrl"):
                raise SharePointError("The configured Invoice Library has no accessible document drive.")
            if configured_id.startswith("b!") and str(drive_id) != configured_id:
                raise SharePointError("The configured SharePoint drive ID does not belong to Invoice Library.")
            columns = {column.get("displayName"): column for column in self._pages(base + "/columns?$top=200", 500)}
            missing = [name for name in REQUIRED_COLUMNS if name not in columns or not columns[name].get("name")]
            if missing:
                raise SharePointError("Invoice Library is missing required columns: " + ", ".join(missing))
            if "personOrGroup" not in columns["Generated By"]:
                raise SharePointError("The Generated By column must be a Person field.")
            self._drive_id = str(drive_id)
            self._list_id = str(list_id)
            self._library_url = str(library["webUrl"])
            self._columns = columns

    @property
    def library_url(self) -> str:
        self._ensure_schema()
        assert self._library_url is not None
        return self._library_url

    def _field(self, display_name: str) -> str:
        self._ensure_schema()
        assert self._columns is not None
        return str(self._columns[display_name]["name"])

    def _site_users(self) -> Iterable[dict[str, Any]]:
        site = urllib.parse.quote(self.settings.sharepoint_site_id or "", safe=",")
        lists = self._pages(f"/sites/{site}/lists?$select=id,displayName,system&$top=200", self.settings.search_max_items)
        user_list = next((item for item in lists if item.get("displayName") == "User Information List"), None)
        if not user_list:
            return ()
        list_id = urllib.parse.quote(str(user_list["id"]), safe="")
        return self._pages(f"/sites/{site}/lists/{list_id}/items?$expand=fields&$top=200", self.settings.search_max_items)

    def resolve_generated_by(self, actor: GenerationActor) -> int:
        """Resolve an actual site Person lookup ID; never submit a fabricated user."""
        keys = [value.casefold() for value in (actor.aad_object_id, actor.email) if value]
        for key in keys:
            if key in self.settings.user_lookup_ids:
                return self.settings.user_lookup_ids[key]
        real_aad_id = False
        try:
            real_aad_id = bool(actor.aad_object_id and UUID(actor.aad_object_id).int)
        except (ValueError, AttributeError):
            pass
        if actor.email or real_aad_id:
            for user in self._site_users():
                fields = user.get("fields") or {}
                identifiers = (
                    fields.get("EMail"), fields.get("Email"), fields.get("UserName"),
                    fields.get("Name"), fields.get("AadObjectId"), fields.get("AADObjectId"),
                    fields.get("AzureADObjectId"), fields.get("UserId"),
                )
                if any(value and any(key in (str(value).casefold(), str(value).casefold().rsplit("|", 1)[-1]) for key in keys) for value in identifiers):
                    try:
                        lookup_id = int(user["id"])
                    except (KeyError, TypeError, ValueError):
                        continue
                    logger.info("generated_by_resolved source=site_user_lookup")
                    return lookup_id
        if self.settings.generated_by_lookup_id:
            logger.info("generated_by_resolved source=configured_fallback_person")
            return self.settings.generated_by_lookup_id
        raise SharePointError("The current user could not be resolved to an Invoice Library Person. Configure a real site user's lookup ID in SHAREPOINT_GENERATED_BY_LOOKUP_ID for local development.")

    def preflight(self, actor: GenerationActor) -> int:
        self._ensure_schema()
        return self.resolve_generated_by(actor)

    def _metadata(self, invoice: Invoice, person_lookup_id: int) -> dict[str, Any]:
        return {
            self._field("Invoice Number"): invoice.invoice_number,
            self._field("Generated Date"): invoice.generated_at.isoformat(),
            self._field("Purpose"): invoice.purpose,
            self._field("Invoice Type"): invoice.invoice_type,
            self._field("Batch ID"): invoice.batch_id,
            self._field("Generated By") + "LookupId": str(person_lookup_id),
            self._field("Seller Name"): invoice.seller.name,
            self._field("Buyer Name"): invoice.buyer.name,
            self._field("Total Amount"): float(invoice.totals.grand_total),
            self._field("Tax Type"): invoice.totals.tax.tax_type,
        }

    def upload_invoice(self, invoice: Invoice, pdf_bytes: bytes, person_lookup_id: int) -> StoredInvoice:
        self._ensure_schema()
        assert self._drive_id is not None
        filename = invoice.invoice_number + ".pdf"
        if not re.fullmatch(r"INV_[A-Z0-9_]+\.pdf", filename):
            raise SharePointError("An unsafe invoice filename was rejected.")
        drive_id = urllib.parse.quote(self._drive_id, safe="")
        uploaded = self.graph.upload_unique(self._drive_id, filename, pdf_bytes)
        drive_item_id = uploaded.get("id")
        if not drive_item_id:
            raise SharePointError("SharePoint did not return an uploaded file ID.")
        logger.info("sharepoint_upload_succeeded invoice_number=%s batch_id=%s", invoice.invoice_number, invoice.batch_id)
        try:
            list_item_id = (uploaded.get("sharepointIds") or {}).get("listItemId")
            if not list_item_id:
                relation = self.graph.request("GET", f"/drives/{drive_id}/items/{urllib.parse.quote(str(drive_item_id), safe='')}/listItem")
                list_item_id = relation.get("id")
            if not list_item_id:
                raise SharePointError("SharePoint did not return a library item ID for the uploaded PDF.")
            self.update_invoice_metadata(str(list_item_id), invoice, person_lookup_id)
            item = self.get_invoice(str(list_item_id))
            if not item.web_url:
                raise SharePointError("SharePoint did not return a link for the stored invoice.")
            logger.info("sharepoint_metadata_succeeded invoice_number=%s item_id=%s", invoice.invoice_number, list_item_id)
            return StoredInvoice(invoice=invoice, item_id=str(list_item_id), web_url=item.web_url)
        except Exception:
            logger.exception("sharepoint_metadata_failed invoice_number=%s", invoice.invoice_number)
            try:
                self.graph.request("DELETE", f"/drives/{drive_id}/items/{urllib.parse.quote(str(drive_item_id), safe='')}")
            except Exception:
                logger.exception("sharepoint_cleanup_failed invoice_number=%s drive_item_id=%s", invoice.invoice_number, drive_item_id)
            raise

    def update_invoice_metadata(self, item_id: str, invoice: Invoice, person_lookup_id: int) -> None:
        fields = self._metadata(invoice, person_lookup_id)
        path = self._base() + f"/items/{urllib.parse.quote(item_id, safe='')}/fields"
        self.graph.request("PATCH", path, fields)
        actual = self.graph.request("GET", self._base() + f"/items/{urllib.parse.quote(item_id, safe='')}?$expand=fields").get("fields") or {}
        for name, expected in fields.items():
            value = actual.get(name)
            if value is None or value == "":
                raise SharePointError(f"SharePoint did not retain the {name} metadata field.")
            if name == self._field("Total Amount"):
                if Decimal(str(value)).quantize(Decimal("0.01")) != invoice.totals.grand_total:
                    raise SharePointError("SharePoint stored an incorrect invoice total.")
            elif name != self._field("Generated Date") and str(value).casefold() != str(expected).casefold():
                raise SharePointError(f"SharePoint stored an incorrect {name} metadata value.")

    def _record(self, item: Mapping[str, Any]) -> SearchRecord:
        fields = item.get("fields") or {}
        metadata = {
            name: fields.get(self._field(name) + "LookupId", fields.get(self._field(name)))
            if name == "Generated By" else fields.get(self._field(name))
            for name in REQUIRED_COLUMNS
        }
        return SearchRecord(item_id=str(item.get("id") or ""), web_url=str(item.get("webUrl") or ""), metadata=metadata)

    def get_invoice(self, item_id: str) -> SearchRecord:
        path = self._base() + f"/items/{urllib.parse.quote(item_id, safe='')}?$expand=fields"
        return self._record(self.graph.request("GET", path))

    def get_invoice_by_number(self, invoice_number: str) -> SearchRecord | None:
        return next((record for record in self.search_invoice_metadata(invoice_number) if str(record.metadata["Invoice Number"]).casefold() == invoice_number.casefold()), None)

    def list_batch_invoices(self, batch_id: str) -> list[SearchRecord]:
        return [record for record in self.search_invoice_metadata(batch_id, limit=self.settings.max_batch_size) if str(record.metadata["Batch ID"]).casefold() == batch_id.casefold()]

    def search_invoice_metadata(self, query: str, limit: int = 20) -> list[SearchRecord]:
        self._ensure_schema()
        upper = query.upper()
        invoice_match = re.search(r"\bINV_[A-Z0-9_]+\b", upper)
        batch_match = re.search(r"\bBATCH-[A-Z0-9-]+\b", upper)
        purpose = next((name for name in ("Testing", "UAT", "Demo", "Training", "Development", "Other") if re.search(rf"\b{re.escape(name)}\b", query, re.IGNORECASE)), None)
        today = "today" in query.casefold()
        from datetime import date, datetime
        today_date = date.today()
        path = self._base() + "/items?$expand=fields&$top=200"
        results: list[SearchRecord] = []
        for item in self._pages(path, self.settings.search_max_items):
            record = self._record(item)
            data = record.metadata
            if invoice_match and str(data["Invoice Number"]).upper() != invoice_match.group():
                continue
            if batch_match and str(data["Batch ID"]).upper() != batch_match.group():
                continue
            if purpose and str(data["Purpose"]).casefold() != purpose.casefold():
                continue
            if today:
                try:
                    generated_time = datetime.fromisoformat(str(data["Generated Date"]).replace("Z", "+00:00"))
                    generated_date = generated_time.astimezone().date() if generated_time.tzinfo else generated_time.date()
                except ValueError:
                    continue
                if generated_date != today_date:
                    continue
            if not (invoice_match or batch_match or purpose or today) and query.strip():
                searchable = " ".join(str(value or "") for value in data.values()).casefold()
                if query.casefold() not in searchable:
                    continue
            results.append(record)
            if len(results) >= limit:
                break
        return results

    def get_invoice_web_url(self, item_id: str) -> str:
        return self.get_invoice(item_id).web_url
